name: Build and Publish to NPM
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
   contents: write # Allow workflow to push to repository

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[RELEASE]'))
      || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3 # Uses "GITHUB_TOKEN"
      - uses: actions/setup-node@v3
      - run: git config --global user.name 'TripleStep AB'
      - run: git config --global user.email 'contact@triplestep.se'
      - run: npm version patch -m "[RELEASE] %s" # Bump version number in package.json (including committing to git)
      - run: git push # Allowed to push to repository because of "permissions" above
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run clean
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v2 # Uses "NPM_TOKEN"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          # dry-run: true
          
