name: Build and Publish to NPM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      ${{ (github.event_name == 'push' && startsWith(github.event.head_commit.message, '[RELEASE]'))
      || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3 # Uses "GITHUB_TOKEN"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run clean
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v2 # Uses "NPM_TOKEN"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          # dry-run: true
          
