name: Version Increment
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
   contents: write # Allow workflow to push to repository

jobs:
  version:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[PATCH]')"  # On each commit, bump version (unless commit message starts with "[RELEASE]")
    steps:
      - uses: actions/checkout@v3 # Uses "GITHUB_TOKEN"
      - run: git config --global user.name 'TripleStep AB'
      - run: git config --global user.email 'contact@triplestep.se'
      - run: npm version patch -m "[PATCH] %s" # Bump version number in package.json (including committing to git)
      - run: git push # Allowed to push to repository because of "permissions" above
